services:
  db:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pg_negocio
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    container_name: sistemaFundamentacion_db