package frontend.alternativa;

import java.awt.Frame;

import javax.swing.JOptionPane;

import backend.controladores.AlternativaControlador;
import backend.entidades.Alternativa;
import backend.entidades.Proyecto;

/**
 *
 * @author Daniel Arias
 */
public class AlternativaInterfaz extends javax.swing.JDialog {
    private Proyecto proyecto;
    private AlternativaControlador alternativaControlador;
    private Alternativa alternativa;
    private boolean evaluar = false;

    /**
     * Creates new form AlternativaInterfaz
     */
    public AlternativaInterfaz(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init(parent);
    }

    public AlternativaInterfaz(Frame parent, boolean modal, Proyecto proyecto) {
        super(parent, modal);
        initComponents();
        init(parent);
        cargarDatos(proyecto, null, false);
        initControladores();
    }

    public AlternativaInterfaz(Frame parent, boolean modal, Proyecto proyecto, Alternativa alternativa,
            boolean evaluar) {
        super(parent, modal);
        initComponents();
        init(parent);
        cargarDatos(proyecto, alternativa, evaluar);
        initControladores();
        cargarDatos(proyecto, alternativa, evaluar);
    }

    private void init(Frame parent) {
        this.setLocationRelativeTo(parent);
        this.setTitle("Crear Alternativa");
    }

    private void cargarDatos(Proyecto proyecto, Alternativa alternativa, boolean evaluar) {
        this.proyecto = proyecto;
        if (alternativa != null) {
            this.alternativa = alternativa;
            txtCategoria.setModel(
                    new javax.swing.DefaultComboBoxModel<>(new String[] { alternativa.getCategoria() }));
            txtCategoria.setSelectedItem(alternativa.getCategoria());
            txtNombre.setText(alternativa.getNombre());
            txtDescripcion.setText(alternativa.getDescripcion());
            txtPros.setText(alternativa.getPros());
            txtContras.setText(alternativa.getContras());
            txtCosto.setText(alternativa.getCosto().toString());
            txtImplementacion.setText(alternativa.getTiempoDeImplementacion().toString());
            txtCategoria.setSelectedItem(alternativa.getCategoria());
            btnCrear.setText("Modificar");
            jLabel2.setText("Modificar Alternativa");
            this.setTitle("Modificar Alternativa");
        }

        if (evaluar) {
            this.evaluar = evaluar;
            txtCategoria.setModel(
                    new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcional", "Pendiente", "Rechazada" }));
            btnCrear.setText("Evaluar");
            jLabel2.setText("Evaluar Alternativa");
            this.setTitle("Evaluar Alternativa");
            txtCategoria.setSelectedItem(alternativa.getCategoria());
            txtNombre.setEditable(false);
            txtDescripcion.setEditable(false);
            txtPros.setEditable(false);
            txtContras.setEditable(false);
            txtCosto.setEditable(false);
            txtImplementacion.setEditable(false);
        }
    }

    private void initControladores() {
        alternativaControlador = new AlternativaControlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPros = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtContras = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtImplementacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JComboBox<>();
        btnCrear = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Crear Alternativa");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Descripcion:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        txtDescripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Pros:");

        txtPros.setColumns(20);
        txtPros.setLineWrap(true);
        txtPros.setRows(5);
        txtPros.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtPros);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Contras:");

        txtContras.setColumns(20);
        txtContras.setLineWrap(true);
        txtContras.setRows(5);
        txtContras.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtContras);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tiemplo de Implementación:");

        txtImplementacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Categoria:");

        txtCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente" }));

        btnCrear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Costo:");

        txtCosto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 647,
                                                Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtNombre))
                                        .addComponent(jScrollPane1)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jScrollPane3)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(btnCrear))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel6))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 270,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtImplementacion)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(txtImplementacion, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCrear)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCrearActionPerformed
        String nombre = txtNombre.getText();
        String descripcion = txtDescripcion.getText();
        String pros = txtPros.getText();
        String contras = txtContras.getText();
        String coString = txtCosto.getText();
        if (nombre.isEmpty() || descripcion.isEmpty() || pros.isEmpty() || contras.isEmpty() || coString.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (alternativa == null && !evaluar) {
            alternativa = new Alternativa();
            alternativa.setNombre(nombre);
            alternativa.setDescripcion(descripcion);
            alternativa.setPros(pros);
            alternativa.setContras(contras);
            alternativa.setCosto(Double.parseDouble(coString));
            alternativa.setTiempoDeImplementacion(Integer.parseInt(txtImplementacion.getText()));
            alternativa.setCategoria(txtCategoria.getSelectedItem().toString());
            alternativa.setIdProyecto(proyecto.getId());
            alternativaControlador.insertar(alternativa);
            this.dispose();
            JOptionPane.showMessageDialog(this, "Alternativa creada con éxito.", "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);
        } else if (alternativa != null && !evaluar) {
            alternativa.setNombre(nombre);
            alternativa.setDescripcion(descripcion);
            alternativa.setPros(pros);
            alternativa.setContras(contras);
            alternativa.setCosto(Double.parseDouble(coString));
            alternativa.setTiempoDeImplementacion(Integer.parseInt(txtImplementacion.getText()));
            alternativa.setCategoria(txtCategoria.getSelectedItem().toString());
            alternativaControlador.actualizar(alternativa);
            this.dispose();
            JOptionPane.showMessageDialog(this, "Alternativa actualizada con éxito.", "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            alternativa.setCategoria(txtCategoria.getSelectedItem().toString());
            alternativaControlador.actualizar(alternativa);
            this.dispose();
            JOptionPane.showMessageDialog(this, "Alternativa evaluada con éxito.", "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);
        }

    }// GEN-LAST:event_btnCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlternativaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlternativaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlternativaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlternativaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlternativaInterfaz dialog = new AlternativaInterfaz(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> txtCategoria;
    private javax.swing.JTextArea txtContras;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtImplementacion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtPros;
    // End of variables declaration//GEN-END:variables
}
